# Use an official Maven and Chrome image
FROM markhobson/maven-chrome

# Set the working directory
WORKDIR /usr/src/app

# Copy the project files into the container
COPY ./mavenproject2\src\main\java\com\mycompany\mavenproject2/ ./

# Build the project
RUN mvn clean install

#Run
sh "maven Mavenproject2"